global:
  resolve_timeout: 5m
  slack_api_url: '${slack_webhook_url}'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

route:
  group_by: ['alertname', 'datacenter']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'pagerduty-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-notifications'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'datacenter']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#consul-alerts'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Datacenter:* {{ .Labels.datacenter }}
          {{ end }}

  - name: 'pagerduty-critical'
    pagerduty_configs:
      - routing_key: '${pagerduty_routing_key}'
        send_resolved: true
        client: 'Consul Federation Monitoring'
        client_url: '${grafana_url}'
        description: >-
          [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Datacenter: {{ .Labels.datacenter }}
          {{ end }}
